nginx:
  kind: Daemon
  image: nginx
  config: /lithos/nginx.yaml
  instances: 1
redis:
  kind: Daemon
  image: redis
  config: /lithos/redis.yaml
  instances: 1
sphinx:
  kind: Daemon
  image: sphinx
  config: /lithos/sphinx.yaml
  instances: 1
