user_id: 1
group-id: 1
volumes:
  /state: !Statedir {}
  /tmp: !Tmpfs
    size: 128Mi
    mode: 0o1777
  /storage: !Persistent
    path: /storage/uwsgi
    mkdir: true
    mode: 0o700
    user: 1
    group: 1
  /log: !Persistent
    path: /log/uwsgi
    mkdir: true
    mode: 0o700
    user: 1
    group: 1
environ:
  PYTHONPATH: /config/python
  DJANGO_SETTINGS_MODULE: app
fileno-limit: 50ki
memory-limit: 1Gi
cpu-shares: 1024
executable: /usr/sbin/uwsgi
arguments:
- /config/uwsgi/uwsgi.ini
