image-dir: /opt/ponyFiction/trunk/images
readonly-paths:
  /config: /opt/ponyFiction/trunk/config
  /srv: /opt/ponyFiction/trunk/srv
writable-paths:
  /storage: /opt/ponyFiction/trunk/storage
  /log: /var/log/ponyFiction/trunk
allow-users: [1]
allow-groups: [0]
