user_id: 1
volumes:
  /tmp: !Tmpfs
    size: 64Mi
    mode: 0o1777
  /config: !Readonly /config
environ:
  PYTHONPATH: $PYTHONPATH:/config
  DJANGO_SETTINGS_MODULE: trunk
fileno-limit: 50ki
memory-limit: 2Gi
cpu-shares: 1024
executable: /usr/local/bin/celery
arguments:
- worker
- -A
- ponyFiction
- --loglevel=INFO