kind: Command
user_id: 1
volumes:
  /tmp: !Tmpfs
    size: 128Mi
    mode: 0o1777
  /log: !Persistent
    path: /log/mysql
  /storage: !Persistent
    path: /storage/mysql
  /config: !Readonly /config
  /srv: !Readonly /srv
environ:
  DB_DATABASE: stories
  DB_USERNAME: celestia
  DB_PASSWORD: solar_eclipse
fileno-limit: 50ki
memory-limit: 2Gi
cpu-shares: 1024
executable: /bin/sh
arguments:
- -c
- |
  if [ "$#" = 1 ] ; then
    echo "Run MySQL in background"
    mysqld_safe --defaults-extra-file=/config/mysql.conf --skip-syslog --no-auto-restart
    while [ ! -f /tmp/mysqld.pid ]; do sleep 0.1; done # wait for server to be ready
    case "$1" in
      *.gz )
        echo "Loading compressed data from $1"
        viewer=zcat
        ;;
      *)
        echo "Loading raw data from $1"
        viewer=cat
        ;;
    esac
    $viewer $1 | mysql \
      --defaults-extra-file=/config/mysql.conf \
      --user=$DB_USERNAME \
      --password=$DB_PASSWORD \
      --database=$DB_DATABASE
    mysqladmin --defaults-extra-file=/config/mysql.conf -uroot -proot shutdown
  else
    echo "No data provided"
  fi
- --
