user_id: 1
volumes:
  /tmp: !Tmpfs
    size: 128Mi
    mode: 0o1777
  /var/log/nginx: !Tmpfs
    size: 1Mi
    mode: 0o1777
  /log: !Persistent
    path: /log/nginx
  /config: !Readonly /config
fileno-limit: 50ki
memory-limit: 1Gi
cpu-shares: 1024
executable: /usr/sbin/nginx
arguments:
- -c
- /config/nginx.conf

