user_id: 1
volumes:
  /tmp: !Tmpfs
    size: 128Mi
    mode: 0o1777
  /log: !Persistent
    path: /log/sphinx
  /storage: !Persistent
    path: /storage/sphinx
  /config: !Readonly /config
fileno-limit: 50ki
memory-limit: 1Gi
cpu-shares: 1024
executable: /usr/bin/searchd
arguments:
- --console
- --config
- /config/sphinx.conf